// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoyozcrcazwxpszlrdzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlveW96Y3JjYXp3eHBzemxyZHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzMwNzUsImV4cCI6MjA3NDU0OTA3NX0.6L_5HEjfpCtRhPfNeEQjoEPJNhBBkOXaB8fQ2ot0V30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});